### ISSUE TITLE
Signal Error 9

### ISSUE THREAD

**Issue by qroft** [LukeTowers/oc-snappypdf-plugin#10]
I have a CMS page with a simple button calling the following onPDF function:
```
function onPDF() {
    trace_log("test");
    $renderedHtml = "Test";
    $pdf = SnappyPDF::loadHTML($renderedHtml)
        ->setOption('margin-top', 0)
        ->setOption('margin-bottom', 0)
        ->setOption('margin-left', 0)
        ->setOption('margin-right', 0)
        ->setPaper('letter')
        ->save("test.pdf");

    return Response::make($pdf, 2, [
        "Content-Type"        => "application/pdf",
        "Content-Disposition" => "filename=test.pdf",
    ]);
}
```

The result is that i get the following error (i have shortend the path):

**"The process has been signaled with signal "9"." on line 429 of /mnt/.../htdocs/octobercms/vendor/symfony/process/Process.php"**

On some pages i have read that this might be a RAM problem as Symfony killed the process.
The project on that i want to use the code is on a shared host.

Is this realy a memory_limit problem or am i missing something?
Greetings and thanks for your time and help guys.

**Comment by LukeTowers** [comment]
@qroft what's the full stack trace? It should give you the command it run, try running the command directly on your server.

**Comment by qroft** [comment]
I don't get the typical stack trace whenever an error occurs.
My code is inside the PHP code part of the page and all i get is that error information as flash message.
:(
Can you direct me into how to make a snapshot/image instead of a PDF with the code above?
Maybe it is the PDF conversion, i am not sure.

**Comment by LukeTowers** [comment]
Just put the entire thing in here. Illuminate is Laravel, so it shouldn't be causing the problem.

**Comment by qroft** [comment]
Symfony\Component\Process\Exception\RuntimeException: The process has been signaled with signal "9". in /mnt/web40909/htdocs/2017-octobercms/vendor/symfony/process/Process.php:429
Stack trace:
#0 /mnt/web40909/htdocs/2017-octobercms/vendor/symfony/process/Process.php(211): Symfony\Component\Process\Process->wait()
#1 /mnt/web40909/htdocs/2017-octobercms/plugins/luketowers/snappypdf/vendor/knplabs/knp-snappy/src/Knp/Snappy/AbstractGenerator.php(529): Symfony\Component\Process\Process->run()
#2 /mnt/web40909/htdocs/2017-octobercms/plugins/luketowers/snappypdf/vendor/knplabs/knp-snappy/src/Knp/Snappy/AbstractGenerator.php(176): Knp\Snappy\AbstractGenerator->executeCommand('/mnt/web40909/...')
#3 /mnt/web40909/htdocs/2017-octobercms/plugins/luketowers/snappypdf/vendor/knplabs/knp-snappy/src/Knp/Snappy/Pdf.php(63): Knp\Snappy\AbstractGenerator->generate(Array, '/var/tmp/knp_sn...', Array, false)
#4 /mnt/web40909/htdocs/2017-octobercms/plugins/luketowers/snappypdf/vendor/knplabs/knp-snappy/src/Knp/Snappy/AbstractGenerator.php(221): Knp\Snappy\Pdf->generate(Array, '/var/tmp/knp_sn...', Array)
#5 /mnt/web40909/htdocs/2017-octobercms/plugins/luketowers/snappypdf/vendor/knplabs/knp-snappy/src/Knp/Snappy/AbstractGenerator.php(242): Knp\Snappy\AbstractGenerator->getOutput(Array, Array)
#6 /mnt/web40909/htdocs/2017-octobercms/plugins/luketowers/snappypdf/vendor/barryvdh/laravel-snappy/src/PdfWrapper.php(176): Knp\Snappy\AbstractGenerator->getOutputFromHtml('hasdf', Array)
#7 /mnt/web40909/htdocs/2017-octobercms/plugins/luketowers/snappypdf/vendor/barryvdh/laravel-snappy/src/PdfWrapper.php(216): Barryvdh\Snappy\PdfWrapper->output()
#8 /mnt/web40909/htdocs/2017-octobercms/storage/cms/cache/10/77/home.htm.php(17): Barryvdh\Snappy\PdfWrapper->download('bla.pdf')
#9 /mnt/web40909/htdocs/2017-octobercms/modules/cms/classes/Controller.php(857): Cms5f4c41188f1b8726507778_068d280698dd6fd71e3d497e9b23b1a3Class->onSnappy()
#10 /mnt/web40909/htdocs/2017-octobercms/modules/cms/classes/Controller.php(739): Cms\Classes\Controller->runAjaxHandler('onSnappy')
#11 /mnt/web40909/htdocs/2017-octobercms/modules/cms/classes/Controller.php(372): Cms\Classes\Controller->execAjaxHandlers()
#12 /mnt/web40909/htdocs/2017-octobercms/modules/cms/classes/Controller.php(223): Cms\Classes\Controller->runPage(Object(Cms\Classes\Page))
#13 /mnt/web40909/htdocs/2017-octobercms/modules/cms/classes/CmsController.php(50): Cms\Classes\Controller->run('/')
#14 [internal function]: Cms\Classes\CmsController->run('/')
#15 /mnt/web40909/htdocs/2017-octobercms/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#16 /mnt/web40909/htdocs/2017-octobercms/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('run', Array)
#17 /mnt/web40909/htdocs/2017-octobercms/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Cms\Classes\CmsController), 'run')
#18 /mnt/web40909/htdocs/2017-octobercms/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\Routing\Route->runController()
#19 /mnt/web40909/htdocs/2017-octobercms/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Route->run()
#20 /mnt/web40909/htdocs/2017-octobercms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#21 /mnt/web40909/htdocs/2017-octobercms/plugins/rainlab/translate/classes/LocaleMiddleware.php(29): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#22 /mnt/web40909/htdocs/2017-octobercms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): RainLab\Translate\Classes\LocaleMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#23 /mnt/web40909/htdocs/2017-octobercms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 /mnt/web40909/htdocs/2017-octobercms/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#25 /mnt/web40909/htdocs/2017-octobercms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /mnt/web40909/htdocs/2017-octobercms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 /mnt/web40909/htdocs/2017-octobercms/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#28 /mnt/web40909/htdocs/2017-octobercms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /mnt/web40909/htdocs/2017-octobercms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 /mnt/web40909/htdocs/2017-octobercms/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#31 /mnt/web40909/htdocs/2017-octobercms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /mnt/web40909/htdocs/2017-octobercms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 /mnt/web40909/htdocs/2017-octobercms/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#34 /mnt/web40909/htdocs/2017-octobercms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /mnt/web40909/htdocs/2017-octobercms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 /mnt/web40909/htdocs/2017-octobercms/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#37 /mnt/web40909/htdocs/2017-octobercms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 /mnt/web40909/htdocs/2017-octobercms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 /mnt/web40909/htdocs/2017-octobercms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#40 /mnt/web40909/htdocs/2017-octobercms/vendor/laravel/framework/src/Illuminate/Routing/Router.php(660): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#41 /mnt/web40909/htdocs/2017-octobercms/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#42 /mnt/web40909/htdocs/2017-octobercms/vendor/laravel/framework/src/Illuminate/Routing/Router.php(601): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#43 /mnt/web40909/htdocs/2017-octobercms/vendor/october/rain/src/Router/CoreRouter.php(20): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#44 /mnt/web40909/htdocs/2017-octobercms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): October\Rain\Router\CoreRouter->dispatch(Object(Illuminate\Http\Request))
#45 /mnt/web40909/htdocs/2017-octobercms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#46 /mnt/web40909/htdocs/2017-octobercms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#47 /mnt/web40909/htdocs/2017-octobercms/vendor/october/rain/src/Foundation/Http/Middleware/CheckForMaintenanceMode.php(25): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 /mnt/web40909/htdocs/2017-octobercms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): October\Rain\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 /mnt/web40909/htdocs/2017-octobercms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 /mnt/web40909/htdocs/2017-octobercms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#51 /mnt/web40909/htdocs/2017-octobercms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#52 /mnt/web40909/htdocs/2017-octobercms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#53 /mnt/web40909/htdocs/2017-octobercms/index.php(43): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#54 {main}

**Comment by LukeTowers** [comment]
@qroft can you post your full code? It's referencing an `onSnappy()` method.

**Comment by qroft** [comment]
I have a button on my home page that looks like this:
`<button data-request="onSnappy" class="ui icon button">Click me for snappy</button>`

And the function inside the PHP code part looks like this:
`function onSnappy() {
    $storagePath =  storage_path('app/uploads/');
    $pdf_file_name =  'nope.pdf' ;
    $pdf_file_name_directory =  $storagePath . $pdf_file_name;

    $pdfSnappy = SnappyPDF::loadHTML("hasdf")
            ->setOption('margin-top', 0)
            ->setOption('margin-bottom', 0)
            ->setOption('margin-left', 0)
            ->setOption('margin-right', 0)
            ->setPaper('letter')
            ->download("test.pdf");
}`

**Comment by LukeTowers** [comment]
"hasdf" is not valid HTML @qroft

**Comment by qroft** [comment]
Maybe no in your country! Just kidding - you are absolutely right!!!!!
Thanks ang big hugs from this corner of the planet!

**Comment by LukeTowers** [comment]
So does that solve your problem then @qroft?
